import { getUserAvatarUrl } from "@/features/auth/model/userAvatar";
import { apiRequest } from "@/shared/api/client";

import type { ActivityEntry, Comment } from "../model/types";
import { getCachedTaskProjectId } from "./tasksApi";

interface ApiUserSummary {
  avatarUrl: string | null;
  id: string;
  name: string;
}

interface ApiComment {
  author: ApiUserSummary;
  body: string;
  createdAt: string;
  id: string;
  taskId: string;
  updatedAt: string;
}

interface ApiActivity {
  actor: ApiUserSummary;
  createdAt: string;
  field: string;
  from: string | null;
  id: string;
  taskId: string;
  to: string | null;
}

interface ApiCommentList {
  data: ApiComment[];
}

interface ApiActivityList {
  data: ApiActivity[];
}

function getProjectIdOrThrow(taskId: string) {
  const projectId = getCachedTaskProjectId(taskId);
  if (!projectId)
    throw new Error("Task must be loaded before comments can be loaded");
  return projectId;
}

function toUser(user: ApiUserSummary) {
  return {
    avatarUrl: getUserAvatarUrl(user),
    id: user.id,
    name: user.name,
  };
}

function toComment(comment: ApiComment): Comment {
  const author = toUser(comment.author);
  return {
    author,
    authorId: author.id,
    body: comment.body,
    createdAt: comment.createdAt,
    id: comment.id,
    isEdited: comment.updatedAt !== comment.createdAt,
    taskId: comment.taskId,
    updatedAt: comment.updatedAt,
  };
}

function toActivity(activity: ApiActivity): ActivityEntry {
  const actor = toUser(activity.actor);
  return {
    actor,
    actorId: actor.id,
    createdAt: activity.createdAt,
    field: activity.field,
    from: activity.from ?? "",
    id: activity.id,
    taskId: activity.taskId,
    to: activity.to ?? "",
  };
}

export async function getCommentsByTaskId(taskId: string): Promise<Comment[]> {
  const projectId = getProjectIdOrThrow(taskId);
  const response = await apiRequest<ApiCommentList>(
    `/projects/${projectId}/tasks/${taskId}/comments`,
  );
  return response.data.map(toComment);
}

export async function createComment(
  taskId: string,
  body: string,
): Promise<Comment> {
  const projectId = getProjectIdOrThrow(taskId);
  const created = await apiRequest<ApiComment>(
    `/projects/${projectId}/tasks/${taskId}/comments`,
    {
      body: JSON.stringify({ body }),
      method: "POST",
    },
  );
  return toComment(created);
}

export async function updateComment(
  commentId: string,
  body: string,
): Promise<Comment> {
  void commentId;
  void body;
  throw new Error("Comment editing is not available in the backend yet");
}

export async function deleteComment(commentId: string): Promise<void> {
  void commentId;
  throw new Error("Comment deletion is not available in the backend yet");
}

export async function getActivityByTaskId(
  taskId: string,
): Promise<ActivityEntry[]> {
  const projectId = getProjectIdOrThrow(taskId);
  const response = await apiRequest<ApiActivityList>(
    `/projects/${projectId}/tasks/${taskId}/activities`,
  );
  return response.data.map(toActivity);
}

export async function logActivityApi(
  taskId: string,
  field: string,
  from: string,
  to: string,
  fromAvatar?: string,
  toAvatar?: string,
) {
  void taskId;
  void field;
  void from;
  void to;
  void fromAvatar;
  void toAvatar;
  throw new Error("Manual activity logging is not available in the backend");
}

export function logActivity() {
  // Activity entries are generated by the backend when tasks/comments mutate.
}
